# Generated by Django 4.1.1 on 2022-10-27 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0005_productattribute_productattributevalue_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productinventory',
            options={'verbose_name': 'product inventory', 'verbose_name_plural': 'product inventories'},
        ),
    ]
