# Generated by Django 4.1.1 on 2022-11-02 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0008_producttype_product_type_attributes'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='cover_photo',
            field=models.ImageField(blank=True, null=True, upload_to='categories/cover_photos'),
        ),
    ]
