# Generated by Django 4.1.1 on 2022-11-03 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0009_category_cover_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinventory',
            name='is_on_sale',
            field=models.BooleanField(default=False, help_text='format: true=product is on sale', verbose_name='is the product on sale'),
        ),
    ]
