# Generated by Django 4.1.1 on 2022-11-04 00:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0010_productinventory_is_on_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttypeattribute',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='category', to='ecommerce.category'),
        ),
    ]
