# Generated by Django 4.1.1 on 2022-11-04 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0011_producttypeattribute_category'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='producttypeattribute',
            unique_together={('product_attribute', 'product_type', 'category')},
        ),
    ]
