# Generated by Django 4.1.1 on 2022-11-10 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0012_alter_producttypeattribute_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='image',
            field=models.ImageField(help_text='format: required, default-default.png', upload_to='products/', verbose_name='product image'),
        ),
    ]
