# Generated by Django 4.1.1 on 2022-11-22 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0016_alter_cart_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='product_inventory',
        ),
        migrations.AddField(
            model_name='cart',
            name='product_inventory',
            field=models.ManyToManyField(to='ecommerce.productinventory'),
        ),
    ]
