# Generated by Django 4.1.1 on 2022-11-22 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0017_remove_cart_product_inventory_cart_product_inventory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='product_inventory',
        ),
        migrations.AddField(
            model_name='cart',
            name='product_inventory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ecommerce.productinventory'),
        ),
    ]
