# Generated by Django 4.1.1 on 2022-11-22 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0018_remove_cart_product_inventory_cart_product_inventory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='product_inventory',
        ),
        migrations.AddField(
            model_name='cart',
            name='product_inventory',
            field=models.ManyToManyField(to='ecommerce.productinventory'),
        ),
    ]
