# Generated by Django 4.1.1 on 2022-11-22 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0019_remove_cart_product_inventory_cart_product_inventory'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, max_digits=2)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=4)),
                ('product_inventory', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='ecommerce.productinventory')),
            ],
        ),
        migrations.RemoveField(
            model_name='cart',
            name='product_inventory',
        ),
        migrations.AlterField(
            model_name='order',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='tax',
            name='tax_percentage',
            field=models.PositiveIntegerField(),
        ),
        migrations.DeleteModel(
            name='OrderedItem',
        ),
        migrations.AddField(
            model_name='cart',
            name='order_item',
            field=models.ManyToManyField(to='ecommerce.orderitem'),
        ),
    ]
