# Generated by Django 4.1.1 on 2022-11-22 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0020_orderitem_remove_cart_product_inventory_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='order_item',
            new_name='order_items',
        ),
    ]
