# Generated by Django 4.1.1 on 2022-11-23 22:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0025_cart_total_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='tax',
            name='product_type',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='ecommerce.producttype'),
        ),
    ]
