# Generated by Django 4.1.1 on 2022-11-23 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0026_tax_product_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tax',
            name='product_type',
        ),
        migrations.AddField(
            model_name='tax',
            name='product_type',
            field=models.ManyToManyField(to='ecommerce.producttype'),
        ),
    ]
