# Generated by Django 4.1.1 on 2022-11-24 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0028_orderitem_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='order_items',
        ),
        migrations.AddField(
            model_name='cart',
            name='order_items',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ecommerce.orderitem'),
        ),
    ]
