# Generated by Django 4.1.1 on 2022-11-28 20:36

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0031_remove_cart_order_items_orderitem_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='total_tax_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=6),
        ),
    ]
