# Generated by Django 4.1.1 on 2022-11-28 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0033_alter_order_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='tax_data',
        ),
        migrations.RemoveField(
            model_name='order',
            name='total_data',
        ),
        migrations.AddField(
            model_name='order',
            name='cart',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ecommerce.cart'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_tax',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
