# Generated by Django 4.1.1 on 2022-11-29 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0035_remove_order_cart_placedorder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='placedorder',
            name='order_items',
        ),
        migrations.AddField(
            model_name='placedorder',
            name='order_items',
            field=models.JSONField(null=True),
        ),
    ]
