# Generated by Django 4.1.1 on 2022-12-12 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0008_alter_postcategory_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=400, unique=True),
        ),
        migrations.AlterField(
            model_name='postcategory',
            name='name',
            field=models.CharField(help_text='format: required, max=100', max_length=100, unique=True, verbose_name='category name'),
        ),
    ]
