# Generated by Django 4.1.1 on 2022-12-13 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0009_alter_post_title_alter_postcategory_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='postcategory',
            name='cover_photo',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
