# Generated by Django 4.1.1 on 2022-12-13 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0010_postcategory_cover_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='cover_photo',
            field=models.ImageField(blank=True, null=True, upload_to='posts/cover_photos'),
        ),
        migrations.AlterField(
            model_name='postcategory',
            name='cover_photo',
            field=models.ImageField(blank=True, null=True, upload_to='post_categories/cover_photos'),
        ),
    ]
