# Generated by Django 4.1.1 on 2022-10-03 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_subscriber_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='info_font_color',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
