# Generated by Django 4.1.1 on 2022-10-04 15:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_messagetostaff'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='messagetostaff',
            options={'ordering': ['date'], 'verbose_name_plural': 'Messages to staff'},
        ),
        migrations.AddField(
            model_name='messagetostaff',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
