# Generated by Django 4.1.1 on 2022-10-04 18:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_messagetostaff_options_messagetostaff_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='messagetostaff',
            options={'ordering': ['-date'], 'verbose_name_plural': 'Messages to staff'},
        ),
        migrations.CreateModel(
            name='ResponseToUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=150)),
                ('content', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('original_message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.messagetostaff')),
                ('staff_member', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Responses',
                'ordering': ['-date'],
            },
        ),
    ]
