# Generated by Django 4.1.1 on 2022-10-05 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_responsetouser_original_message_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ResponseToUser',
        ),
    ]
