# Generated by Django 4.1.1 on 2022-10-10 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0003_message_is_read'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='is_read',
        ),
    ]
