# Generated by Django 4.1.1 on 2022-12-15 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0005_alter_chatroom_options_chatroom_updated_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatroom',
            options={},
        ),
        migrations.RemoveField(
            model_name='chatroom',
            name='updated_at',
        ),
    ]
